export const productVersion = "0.5.0";

export const capabilities = [
  {
    slug: "source-catalog",
    name: "高价值信源目录",
    domain: "sensing",
    status: "operational",
    maturity: 68,
    release: "0.2.0",
    evidence: "258 sources classified by region, role, acquisition and maintenance state",
  },
  {
    slug: "upstream-discovery",
    name: "聚合上游发现",
    domain: "sensing",
    status: "experimental",
    maturity: 56,
    release: "0.3.0",
    evidence: "aggregator observations are stored as discoveries and matched to direct publishers",
  },
  {
    slug: "continuous-data-refresh",
    name: "持续数据刷新",
    domain: "sensing",
    status: "experimental",
    maturity: 58,
    release: "0.4.0",
    evidence:
      "scheduled GitHub Actions collection with serialized writes and explicit Pages dispatch",
  },
  {
    slug: "two-year-baseline",
    name: "两年行业基线",
    domain: "understanding",
    status: "experimental",
    maturity: 62,
    release: "0.4.0",
    evidence: "30 source-backed milestones from 2024-07 to 2026-05 plus current 2026 events",
  },
  {
    slug: "track-synthesis",
    name: "主线阶段收敛",
    domain: "intelligence",
    status: "operational",
    maturity: 66,
    release: "0.4.0",
    evidence: "five eras and six executive track narratives with China-position comparisons",
  },
  {
    slug: "primary-source-gate",
    name: "一手事实门禁",
    domain: "governance",
    status: "operational",
    maturity: 65,
    release: "0.3.0",
    evidence: "aggregator-role collectors cannot write factual signals or enter event clustering",
  },
  {
    slug: "source-lifecycle",
    name: "信源生命周期",
    domain: "sensing",
    status: "operational",
    maturity: 62,
    release: "0.2.0",
    evidence: "draft/shadow/active/degraded/quarantined/retired state machine",
  },
  {
    slug: "resilient-fetch",
    name: "弹性拉取",
    domain: "sensing",
    status: "operational",
    maturity: 72,
    release: "0.2.0",
    evidence:
      "direct-first fetch with bounded fallback proxy, timeout, retry classification, backoff, cache, per-host rate limit and redirect guard",
  },
  {
    slug: "source-observability",
    name: "来源可观测性",
    domain: "sensing",
    status: "operational",
    maturity: 70,
    release: "0.2.0",
    evidence:
      "append-only checks for access, fetch, parse, schema, volume, freshness, duplicates, quality, proxy, repair and retention with admin history",
  },
  {
    slug: "source-audit",
    name: "逐源恢复审计",
    domain: "sensing",
    status: "operational",
    maturity: 68,
    release: "0.5.0",
    evidence:
      "259/259 live rows checked; 131 healthy, 120 strict effective and 104 strict realtime effective sources",
  },
  {
    slug: "shadow-observation",
    name: "隔离观察数据池",
    domain: "sensing",
    status: "operational",
    maturity: 58,
    release: "0.5.0",
    evidence:
      "99 qualified shadow sources supply an isolated observation pool; their signals cannot enter public events before production promotion",
  },
  {
    slug: "source-contract",
    name: "适配器契约验证",
    domain: "sensing",
    status: "experimental",
    maturity: 36,
    release: "0.1.0",
    evidence: "shared SourceAdapter and partial parser fixtures",
  },
  {
    slug: "incremental-sync",
    name: "增量同步",
    domain: "sensing",
    status: "experimental",
    maturity: 32,
    release: "0.2.0",
    evidence: "ETag and Last-Modified state; cursor/fingerprint pending",
  },
  {
    slug: "coverage-map",
    name: "国内外覆盖地图",
    domain: "sensing",
    status: "experimental",
    maturity: 46,
    release: "0.2.0",
    evidence: "region/category catalog; continuous coverage metrics pending",
  },
  {
    slug: "normalize",
    name: "信号规范化",
    domain: "understanding",
    status: "operational",
    maturity: 58,
    release: "0.1.0",
    evidence: "shared CollectedSignal model and sanitization",
  },
  {
    slug: "dedupe",
    name: "URL 与内容去重",
    domain: "understanding",
    status: "operational",
    maturity: 48,
    release: "0.1.0",
    evidence: "canonical URL/content hash; cross-source observations pending",
  },
  {
    slug: "event-clustering",
    name: "事件聚类",
    domain: "understanding",
    status: "experimental",
    maturity: 48,
    release: "0.1.0",
    evidence:
      "eventability gate, model family/facet fingerprints and reviewable merge candidates; multilingual semantic clustering pending",
  },
  {
    slug: "reversible-signal-triage",
    name: "可逆信号分诊",
    domain: "understanding",
    status: "experimental",
    maturity: 58,
    release: "0.5.0",
    evidence:
      "533 low-eventability signals retained as deferred observations, zero clustering backlog and reversible review snapshots",
  },
  {
    slug: "event-convergence",
    name: "人工事件收敛",
    domain: "understanding",
    status: "experimental",
    maturity: 50,
    release: "0.5.0",
    evidence:
      "family/facet merge queue, readiness-aware target selection, explicit confirmation and append-only merge audit",
  },
  {
    slug: "entity-resolution",
    name: "实体与别名对齐",
    domain: "understanding",
    status: "planned",
    maturity: 10,
    release: "future",
    evidence: "actor catalog only",
  },
  {
    slug: "claim-evidence",
    name: "Claim 级证据链",
    domain: "understanding",
    status: "planned",
    maturity: 12,
    release: "future",
    evidence: "event-signal provenance exists; claim mapping pending",
  },
  {
    slug: "fact-reason-impact",
    name: "Fact / Reason / Impact",
    domain: "understanding",
    status: "experimental",
    maturity: 38,
    release: "0.1.0",
    evidence: "event fields exist; automatic reasoning evaluation pending",
  },
  {
    slug: "confidence",
    name: "可信度评分",
    domain: "intelligence",
    status: "experimental",
    maturity: 35,
    release: "0.1.0",
    evidence: "explainable baseline; real calibration set pending",
  },
  {
    slug: "heat",
    name: "跨圈热度判断",
    domain: "intelligence",
    status: "experimental",
    maturity: 24,
    release: "0.1.0",
    evidence: "baseline factors; real cross-platform observation network pending",
  },
  {
    slug: "impact-value",
    name: "影响与价值分析",
    domain: "intelligence",
    status: "experimental",
    maturity: 32,
    release: "0.1.0",
    evidence: "scoring schema and curated examples; outcome calibration pending",
  },
  {
    slug: "trend",
    name: "趋势与拐点识别",
    domain: "intelligence",
    status: "planned",
    maturity: 8,
    release: "future",
    evidence: "timeline grouping only",
  },
  {
    slug: "contradiction",
    name: "反证与冲突检测",
    domain: "intelligence",
    status: "planned",
    maturity: 5,
    release: "future",
    evidence: "Scout counter-signal field only",
  },
  {
    slug: "scout",
    name: "Opportunity Scout",
    domain: "intelligence",
    status: "experimental",
    maturity: 38,
    release: "0.2.0",
    evidence: "evidence-bound deterministic candidates, cooldown and human publication gate",
  },
  {
    slug: "forecast",
    name: "预测与校准",
    domain: "intelligence",
    status: "planned",
    maturity: 0,
    release: "future",
    evidence: "roadmap only",
  },
  {
    slug: "today",
    name: "Today 决策摘要",
    domain: "experience",
    status: "experimental",
    maturity: 36,
    release: "0.1.0",
    evidence: "executive lead from published events",
  },
  {
    slug: "timeline",
    name: "Timeline 主线",
    domain: "experience",
    status: "operational",
    maturity: 55,
    release: "0.1.0",
    evidence: "multi-track static timeline and event drawer",
  },
  {
    slug: "radar",
    name: "Radar 格局观察",
    domain: "experience",
    status: "experimental",
    maturity: 30,
    release: "0.1.0",
    evidence: "actor catalog and visual radar; evidence-based movement pending",
  },
  {
    slug: "inbox",
    name: "Inbox 机会沉淀",
    domain: "experience",
    status: "experimental",
    maturity: 42,
    release: "0.2.0",
    evidence: "Scout status workflow and public/private gate",
  },
  {
    slug: "control-room",
    name: "Control Room",
    domain: "experience",
    status: "experimental",
    maturity: 65,
    release: "0.1.0",
    evidence:
      "source checks, coverage, funnel, blockers, event evidence, merge queue, release gate, source lifecycle, views and Scout controls",
  },
  {
    slug: "publication-readiness",
    name: "发布就绪门禁",
    domain: "governance",
    status: "operational",
    maturity: 66,
    release: "0.5.0",
    evidence:
      "publish API rejects missing primary evidence, placeholders, generic entities, taxonomy gaps, low confidence and unsupported heat",
  },
  {
    slug: "static-release",
    name: "隐私安全静态发布",
    domain: "delivery",
    status: "operational",
    maturity: 70,
    release: "0.1.0",
    evidence: "allowlist JSON export and GitHub Pages workflow",
  },
  {
    slug: "repository-snapshot",
    name: "仓库数据快照",
    domain: "delivery",
    status: "operational",
    maturity: 72,
    release: "0.4.0",
    evidence:
      "deterministic privacy-safe JSON snapshot with merge restore and sensitive URL stripping",
  },
  {
    slug: "release-evolution",
    name: "版本演进与 Changelog",
    domain: "delivery",
    status: "operational",
    maturity: 60,
    release: "0.2.0",
    evidence: "versioned changelog, capability deltas and public evolution spine",
  },
  {
    slug: "evaluation",
    name: "多维评测体系",
    domain: "governance",
    status: "experimental",
    maturity: 56,
    release: "0.2.0",
    evidence:
      "persisted scorecards plus live source audit, coverage and Signal-to-Ready-to-Published funnel with blocker counts",
  },
  {
    slug: "bounded-evolution",
    name: "有界持续进化循环",
    domain: "governance",
    status: "experimental",
    maturity: 54,
    release: "0.5.0",
    evidence:
      "bounded scheduled loop with atomic checkpoints, per-iteration reports, failure isolation, explicit mutation flags and graceful shutdown",
  },
  {
    slug: "security",
    name: "采集与管理安全",
    domain: "governance",
    status: "operational",
    maturity: 66,
    release: "0.1.0",
    evidence: "SSRF guard, body limit, CSP, bearer auth and text rendering",
  },
  {
    slug: "capability-accounting",
    name: "能力资产核算",
    domain: "governance",
    status: "operational",
    maturity: 58,
    release: "0.2.0",
    evidence: "capability map links status, maturity, release and implementation evidence",
  },
] as const;

export const roadmap = [
  {
    state: 1,
    name: "可信时间轴骨架",
    promise: "把分散信号变成可审核、可发布的唯一事件节点。",
    status: "current",
    milestones: [
      "M1 · Node/TypeScript + SQLite 的可复现数据与发布骨架",
      "M2 · Event / Track / Actor / Evidence 基础模型与静态 Timeline",
      "M3 · 管理审核、隐私 allowlist 与 GitHub Pages release 链路",
      "M4 · 用真实数据替换 demo 分数，并补齐后台到发布快照的闭环",
    ],
  },
  {
    state: 2,
    name: "可信感知网络",
    promise: "来源可以长期运行，数据质量和覆盖缺口可以被量化。",
    status: "building",
    milestones: [
      "M1 · 100+ 高质量 Source Catalog 与国内外覆盖 Scorecard",
      "M2 · 生命周期、契约 fixture、重试限流、增量状态与 Source SLO",
      "M3 · Document / Observation 分离，保留跨源传播和媒体矩阵关系",
      "M4 · 调度、漂移检测、fallback、canary 与可回放的来源运维系统",
    ],
  },
  {
    state: 3,
    name: "行业理解与证据洞察",
    promise: "系统不仅知道发生了什么，还能解释关系、冲突和趋势。",
    status: "planned",
    milestones: [
      "M1 · 多语言实体、Claim、Evidence、Contradiction 知识图谱",
      "M2 · Fact / Reason / Impact / Signal / Future 的自动收敛与评测集",
      "M3 · 具备阶段、转折、因果与对比关系的 Narrative Timeline",
      "M4 · Opportunity Scout Beta：证据、反证、反馈和产物闭环",
    ],
  },
  {
    state: 4,
    name: "个人战略与知识网络",
    promise: "把行业变化连接到用户目标、行动和长期个人资产。",
    status: "planned",
    milestones: [
      "M1 · CEO / 投资 / 技术 / 创业关注组合与本地 Owner Profile",
      "M2 · Scout 建议到 48 小时实验、7 日产物和结果复盘",
      "M3 · 认知、作品、关系与影响力的长期资产图谱",
      "M4 · 个性化 weekly decision brief 与弱信号注意力预算",
    ],
  },
  {
    state: 5,
    name: "可校准的 AI 决策副驾",
    promise: "从持续观察走向可验证预测，并在治理边界内自我演进。",
    status: "planned",
    milestones: [
      "M1 · Scenario、领先指标、预测 Ledger 与 Brier 校准",
      "M2 · 自动发现覆盖缺口并提出 Source / Detector / Adapter 改进提案",
      "M3 · Shadow replay、策略 A/B、自动回滚与人工 promotion 治理",
      "M4 · 受预算、权限、审计和人工批准约束的多 Agent 调研网络",
    ],
  },
] as const;

export const releases = [
  {
    version: "0.5.0",
    date: "2026-07-12",
    name: "The Evidence Engine",
    summary: "恢复 100+ 严格有效信源，以隔离观察、诚实评测和证据优先体验重建从供给到决策的链路。",
    capabilities: [
      "100+ 严格实时有效信源",
      "隔离观察数据池",
      "逐源恢复审计",
      "可逆信号分诊",
      "人工事件收敛",
      "诚实评测校准",
      "证据优先时间轴",
      "有界持续进化",
    ],
    changes: [
      "来源目录扩至 258 个；全量实测 131 healthy、120 strict effective、104 strict realtime effective",
      "99 个合格 shadow 来源进入 E3 隔离观察，数据可采集但不会绕过 E4 门禁进入公开事实",
      "建立逐源检查、失败分类、代理降级、质量门禁、可逆 triage、事件合并候选和发布就绪漏斗",
      "评测从目录数量和人工自评分转向真实样本、证据覆盖与硬上限，旧口径 69 分回落到诚实水位",
      "公开页改为 30 秒判断、六条主线和证据优先时间轴；默认事件必须包含一手来源",
      "管理台补齐来源健康、观察开关、漏斗、阻断原因、证据详情、合并队列与校准评测",
    ],
  },
  {
    version: "0.4.0",
    date: "2026-07-11",
    name: "The Industry Arc",
    summary: "从新闻式堆叠转向两年行业主线，并让数据采集、仓库快照与 GitHub Pages 持续联动。",
    capabilities: [
      "持续数据刷新",
      "仓库数据快照",
      "两年行业基线",
      "主线阶段收敛",
      "高密度公开首页",
    ],
    changes: [
      "新增每 6 小时 GitHub Actions 数据刷新；数据变化后提交隐私安全 JSON 快照并显式部署 Pages",
      "建立 2024-07 至 2026-07 行业基线，加入 30 个一手来源里程碑和 5 个发展阶段",
      "将默认公开体验收敛为 Today、六条趋势主线和两年演进摘要，其他工具按需展开",
      "新增中国追赶的阶段性同维度对照，不再只呈现静态公司排名",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-07-11",
    name: "Primary Source Protocol",
    summary: "把聚合站降为发现雷达，让事实、热度和原始发布者各自回到正确的数据层。",
    capabilities: [
      "聚合上游发现",
      "一手事实门禁",
      "来源身份匹配",
      "聚合热度回填",
      "官方价格基线目录",
      "来源候选雷达",
    ],
    changes: [
      "AI HOT、HuggingNews 等聚合器只写 Source Discovery，不再直接生成事实 Signal",
      "按原始 URL、唯一域名和社交账号匹配直接来源，无法匹配的内容进入人工候选队列",
      "补入 AI HOT 背后的官方、研究、专家与专业媒体来源，并扩充至 195 个来源",
      "PriceAI 保留为比较入口，价格改由厂商官网、App Store 与独立汇率源采集",
      "Evaluation 新增一手来源归属维度，持续暴露历史聚合器证据债务",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-07-11",
    name: "The Source & Scout Foundation",
    summary: "从可演示 Timeline 转向可运营来源平台，并第一次把行业信号转化为机会假设。",
    capabilities: [
      "高价值信源目录",
      "信源生命周期",
      "弹性拉取",
      "SourceRun",
      "Opportunity Scout",
      "多维评测",
      "能力资产核算",
    ],
    changes: [
      "建立 100+ 国内外来源目录，并区分 ready、candidate、restricted 与 manual",
      "加入有界并发、瞬时错误重试、条件请求、健康分、自动降级与人工隔离",
      "加入证据型星探、冷却去重、私有 inbox 与人工公开门禁",
      "加入 State 1–5 Roadmap、Capability Map、评测 Scorecard 与公开演进时间轴",
    ],
  },
  {
    version: "0.1.0",
    date: "2026-07-11",
    name: "First Signal",
    summary: "把 Python/JSON 原型重构为 Node/TypeScript 的可运行行业认知骨架。",
    capabilities: ["Event 模型", "多主线 Timeline", "Control Room", "静态发布"],
    changes: [
      "建立 SQLite/MySQL 抽象、migration、统一 SourceAdapter 与 Event pipeline",
      "建立多主线、角色雷达、模型资源和右侧详情抽屉",
      "建立 Fastify 管理 API、静态导出、CI 与 GitHub Pages",
    ],
  },
] as const;
